server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.todolist.pojo.do
  configuration:
    map-underscore-to-camel-case: true
